/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Wazuh;

/**
 *
 * @author javav
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conectar_boton = new javax.swing.JButton();
        grupos_box = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Grupos = new javax.swing.JList<>();
        agentes_box = new javax.swing.JPanel();
        cbox_Agentes = new javax.swing.JComboBox<>();
        lbl_Critical = new javax.swing.JLabel();
        lbl_Alto = new javax.swing.JLabel();
        lbl_Baja = new javax.swing.JLabel();
        lbl_Media = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        vulnerabilidades_Label = new javax.swing.JLabel();
        vulnerabilidades_cbox = new javax.swing.JComboBox<>();
        vulnerabilidades_scroll = new javax.swing.JScrollPane();
        lst_Urls = new javax.swing.JList<>();
        severidad_box = new javax.swing.JPanel();
        rdi_Critica = new javax.swing.JRadioButton();
        rdi_Alta = new javax.swing.JRadioButton();
        rdi_media = new javax.swing.JRadioButton();
        rdi_baja = new javax.swing.JRadioButton();
        rdi_Todo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conectar_boton.setText("Conectar");

        grupos_box.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));

        lst_Grupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_Grupos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_GruposValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_Grupos);

        javax.swing.GroupLayout grupos_boxLayout = new javax.swing.GroupLayout(grupos_box);
        grupos_box.setLayout(grupos_boxLayout);
        grupos_boxLayout.setHorizontalGroup(
            grupos_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupos_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        grupos_boxLayout.setVerticalGroup(
            grupos_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupos_boxLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        agentes_box.setBorder(javax.swing.BorderFactory.createTitledBorder("Agentes"));

        cbox_Agentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_AgentesActionPerformed(evt);
            }
        });

        lbl_Total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout agentes_boxLayout = new javax.swing.GroupLayout(agentes_box);
        agentes_box.setLayout(agentes_boxLayout);
        agentes_boxLayout.setHorizontalGroup(
            agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentes_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_Agentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(agentes_boxLayout.createSequentialGroup()
                        .addGroup(agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Critical, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Alto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Media, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(agentes_boxLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agentes_boxLayout.setVerticalGroup(
            agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentes_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_Agentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(agentes_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentes_boxLayout.createSequentialGroup()
                        .addComponent(lbl_Critical, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Alto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agentes_boxLayout.createSequentialGroup()
                        .addComponent(lbl_Media, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vulnerabilidades_Label.setText("Vulnerabilidades:");

        vulnerabilidades_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vulnerabilidades_cboxActionPerformed(evt);
            }
        });

        lst_Urls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_UrlsMouseClicked(evt);
            }
        });
        vulnerabilidades_scroll.setViewportView(lst_Urls);

        severidad_box.setBorder(javax.swing.BorderFactory.createTitledBorder("Severidad"));

        rdi_Critica.setText("Críticas");
        rdi_Critica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdi_CriticaActionPerformed(evt);
            }
        });

        rdi_Alta.setText("Altas");
        rdi_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdi_AltaActionPerformed(evt);
            }
        });

        rdi_media.setText("Media");
        rdi_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdi_mediaActionPerformed(evt);
            }
        });

        rdi_baja.setText("Baja");
        rdi_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdi_bajaActionPerformed(evt);
            }
        });

        rdi_Todo.setSelected(true);
        rdi_Todo.setText("Todas");
        rdi_Todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdi_TodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout severidad_boxLayout = new javax.swing.GroupLayout(severidad_box);
        severidad_box.setLayout(severidad_boxLayout);
        severidad_boxLayout.setHorizontalGroup(
            severidad_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(severidad_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(severidad_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdi_Critica)
                    .addComponent(rdi_Alta)
                    .addComponent(rdi_media)
                    .addComponent(rdi_baja)
                    .addComponent(rdi_Todo))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        severidad_boxLayout.setVerticalGroup(
            severidad_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(severidad_boxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdi_Todo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdi_Critica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdi_Alta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdi_media)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdi_baja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vulnerabilidades_Label)
                        .addGap(18, 18, 18)
                        .addComponent(vulnerabilidades_cbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(vulnerabilidades_scroll)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grupos_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(agentes_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(severidad_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(conectar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(severidad_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agentes_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupos_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vulnerabilidades_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vulnerabilidades_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(vulnerabilidades_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conectar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lst_GruposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_GruposValueChanged

        
    }//GEN-LAST:event_lst_GruposValueChanged

    private void cbox_AgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_AgentesActionPerformed
       
    }//GEN-LAST:event_cbox_AgentesActionPerformed

    private void vulnerabilidades_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vulnerabilidades_cboxActionPerformed

      
    }//GEN-LAST:event_vulnerabilidades_cboxActionPerformed

    private void lst_UrlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_UrlsMouseClicked
     
    }//GEN-LAST:event_lst_UrlsMouseClicked

    private void rdi_CriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdi_CriticaActionPerformed
      
    }//GEN-LAST:event_rdi_CriticaActionPerformed

    private void rdi_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdi_AltaActionPerformed
      
    }//GEN-LAST:event_rdi_AltaActionPerformed

    private void rdi_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdi_mediaActionPerformed
      
    }//GEN-LAST:event_rdi_mediaActionPerformed

    private void rdi_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdi_bajaActionPerformed
     
    }//GEN-LAST:event_rdi_bajaActionPerformed

    private void rdi_TodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdi_TodoActionPerformed
     
    }//GEN-LAST:event_rdi_TodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agentes_box;
    private javax.swing.JComboBox<String> cbox_Agentes;
    private javax.swing.JButton conectar_boton;
    private javax.swing.JPanel grupos_box;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Alto;
    private javax.swing.JLabel lbl_Baja;
    private javax.swing.JLabel lbl_Critical;
    private javax.swing.JLabel lbl_Media;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JList<String> lst_Grupos;
    private javax.swing.JList<String> lst_Urls;
    private javax.swing.JRadioButton rdi_Alta;
    private javax.swing.JRadioButton rdi_Critica;
    private javax.swing.JRadioButton rdi_Todo;
    private javax.swing.JRadioButton rdi_baja;
    private javax.swing.JRadioButton rdi_media;
    private javax.swing.JPanel severidad_box;
    private javax.swing.JLabel vulnerabilidades_Label;
    private javax.swing.JComboBox<String> vulnerabilidades_cbox;
    private javax.swing.JScrollPane vulnerabilidades_scroll;
    // End of variables declaration//GEN-END:variables
}
